#!/bin/sh

#
# chkconfig: 35 98 98
# description: Node.js server and benchmark tools initialization
#

. /etc/rc.d/init.d/functions

USER="vagrant"
DAEMON="/home/$USER/.nodebrew/current/bin/node"

SERVER_ROOT_DIR="/home/$USER/isucon2/webapp/nodejs"
BENCH_ROOT_DIR="/home/$USER/isucon2/tools"

SERVER="$SERVER_ROOT_DIR/server.js"
MANAGER="$BENCH_ROOT_DIR/manager.js"
AGENT="$BENCH_ROOT_DIR/agent.js"

LOG_FILE="$SERVER_ROOT_DIR/server.js.log"
LOCK_FILE="/var/lock/subsys/node-server"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "cd $SERVER_ROOT_DIR && $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                runuser -l "$USER" -c "cd $BENCH_ROOT_DIR && $DAEMON $MANAGER >> $LOG_FILE &" && echo_success || echo_failure
                runuser -l "$USER" -c "cd $BENCH_ROOT_DIR && $DAEMON $AGENT >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid_server=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        pid_manager=`ps -aefw | grep "$DAEMON $MANAGER" | grep -v " grep " | awk '{print $2}'`
        pid_agent=`ps -aefw | grep "$DAEMON $AGENT" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid_server $pid_manager $pid_agent > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL